name: Windows-win64

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake build
      run: cmake -S . -B build --config Release
    - name: cmake make
      run: cmake --build build --parallel 3
    - name: test
      run: build\Release\aixlog_example.exe
